### ISSUE TITLE
Duplicate hover hints for re-declared functions

### ISSUE THREAD

**Issue by automaticp** [nolanderc/glsl_analyzer#16]
Declaring the same function multiple times produces a hint for each declaration. Quite noticeable if you like to declare helper functions at the top and define them at the bottom.

```glsl
#version 330 core

float foo(float, vec3);
float foo(float, vec3);

void main() {
    foo(1.0, vec3(1.0)); // <- triple hint
}

float foo(float, vec3) { return 1.0; }
```

![image](https://github.com/nolanderc/glsl_analyzer/assets/83063079/ab51ab70-90cf-409b-a304-391ef9a31191)

**Comment by nolanderc** [comment]
Yes, this is an issue with the current name-resolution/type-checking. I have been meaning to rewrite it for a while... Currently it simply does an upwards tree traversal, looking for any definitions that match the current name. In order to support overloading, it currently returns all matches (instead of just the first) since it isn't clever enough to compare the types of the function parameters. However, this is quite a large change, so you'll have to live with this for a while :slightly_frowning_face:

**Comment by automaticp** [comment]
Of course, no pressure. This is totally a minor issue anyways.

**Comment by nolanderc** [comment]
I have an idea on how to fix this: essentially, we just pretty-print the types and compare the strings for equality. It's not totally fool-proof, but likely good enough as a MVP. But I've already done a lot tonight so might leave that for tomorrow.

**Comment by automaticp** [comment]
Yeah, just don't send out identical responses from the same hover request. Maybe even condense multiple overloads into a singe lsp response too. Might be slightly harder to test, but it's rare to see multiple hover pop-ups on a single request. I didn't even know you could have that.

**Comment by nolanderc** [comment]
> it's rare to see multiple hover pop-ups on a single request

Yes, ideally we would know which overload is being used, but without types that is not possible.
I believe vscode gives a more reasonable UI for signature help, which we should also implement.
